### ISSUE TITLE
Seeding Failed

### ISSUE THREAD

**Issue by magusd** [pandaac/apolune#1]
Installed using composer create-project on ubuntu server

php artisan migrate ran smoothly

php artisan db:seed gave me:
```
[Illuminate\Database\QueryException]                                                                                                         
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'world_id' in 'field list' (SQL: insert into `guilds` (`world_id`, `name`, `ownerid`  
  , `creationdata`) values (0, Some Random Guild, 9, 1443036949)) 
```

**Comment by eklundchristopher** [comment]
Oh, cheers! I'll sort it out within the hour. For now however, you could temporarily add a world_id (int) column to your guilds table and remove it once the seeding process is completed.

**Comment by eklundchristopher** [comment]
Should be fixed.

**Comment by magusd** [comment]
Hey there! Ty so much for the quick reply!
I didn't want to run it manually, so I waited.

ran
composer update
php artisan migrate

and it didn't get me anything. Is that right?
I saw you modified Guild.php, does that Guild Entity generates the migration for you?
(I am a Laravel developer myself, that's why I've picked pandacc instead of other account makers)

**Comment by eklundchristopher** [comment]
It may be loading from your cache, try running `composer update pandaac/apolune` and see if it's updating to the latest commit (500ab35). If it is indeed loading from your cache, try running `composer clear-cache` to clear your cache and give it another go.

The guild model itself doesn't handle the migration, there's a separate file for it, however, the guild model assumed that all guild tables have a world_id column, which shouldn't be the case. Another issue I noticed with the seeders were the fact that it would attempt to create a guild even if there weren't any players to pick a leader from.

The news & guild seeds are mainly meant for the demo site, and will eventually be limited to such cases (probably dictated by an environment value), but for now, they'll remain in the default seeding 'group'.

**Comment by magusd** [comment]
Nice! Thanks for the info.
Ran the composer clear-cache and it worked out flawlessly!

I read it was still being migrated to L51, I've preserved the repo to pull your updates and I'll be rebasing my custom changes. Once I figure out your coding style I'll submit pull requests where I see the need!

Thank you for putting such effort on an open source project, it's been of great help!

**Comment by eklundchristopher** [comment]
Glad to hear it worked out for you, and thank you very much for the kind words!

As for the project itself, I'm using the PSR-2 standard. It is also built very similiar to how Laravel is built where Apolune is a collection of repositories much like Illuminate is to Laravel, and the pandaac repository would be the equivalent of the Laravel main repository. The difference however, is that I've added a third element in themes, which is the glue to everything.

Each theme dictates which Apolune repositories (or any other, outsourced repositories) it wants to use. Whether that is the entire Apolune collection or some individual packages is again, completely up to the theme at hand.

Once we're getting closer to a first stable release, I will be putting together a documentation of all the features that pandaac offers. Whether those features are extensions to the Laravel behaviour or completely new features. This documentation would also offer a guide on how to get started with theme and/or package building.

I hope this might be helpful, and I'm looking forward to seeing some of your pull requests in the future! If there's anything else you're wondering about, feel free to create a new issue, contact me through email or OtLand.

Cheers!
